languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon CloudOps Linux Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "Matthew Patrick, John Dixon, Utsav Joshi, Bobby Malik"
description = "Amazon CloudOps Linux Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/dixonaws/aws-cloudops-storage/edit/main/content/"
baseURL = "https://storageworkshop.aws-cloudops.com/index.html"
disableLandingPage=false
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

#

[menu]

[[menu.shortcuts]]
identifier = 'github'
name="<i class='fab fa-github fa-lg'></i> Github Repo"
url = "https://github.com/dixonaws/aws-cloudops-storage"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Matthew Patrick"
identifier = "li0"
url = "https://www.linkedin.com/in/matthew-patrick-capone/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Michael Reiber"
identifier = "li1"
url = "https://www.linkedin.com/in/michael-reiber-44a09735/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Prasanth Ponnoth"
identifier = "li2"
url = "https://www.linkedin.com/in/prasanthponnoth/"
weight = 40

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> Adrian Tarjoianu"
identifier = "li3"
url = "https://www.linkedin.com/in/adriantarjoianu/"
weight = 50



[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]

[markup.goldmark.renderer]
unsafe= true
